//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA_FrontEnd.PaymentValidationReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.oracle.com/ValidatePayment", ConfigurationName="PaymentValidationReference.validatePaymentPortType")]
    public interface validatePaymentPortType {
        
        // CODEGEN: Generating message contract since the operation validate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="validate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA_FrontEnd.PaymentValidationReference.validateResponse validate(SOA_FrontEnd.PaymentValidationReference.validateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="validate", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA_FrontEnd.PaymentValidationReference.validateResponse> validateAsync(SOA_FrontEnd.PaymentValidationReference.validateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oracle.com/soasample")]
    public partial class PaymentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cardPaymentTypeField;
        
        private string cardNumField;
        
        private string expireDateField;
        
        private string cardNameField;
        
        private AddressType billingAddressField;
        
        private System.DateTime authorizationDateField;
        
        private bool authorizationDateFieldSpecified;
        
        private double authorizationAmountField;
        
        private bool authorizationAmountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CardPaymentType {
            get {
                return this.cardPaymentTypeField;
            }
            set {
                this.cardPaymentTypeField = value;
                this.RaisePropertyChanged("CardPaymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CardNum {
            get {
                return this.cardNumField;
            }
            set {
                this.cardNumField = value;
                this.RaisePropertyChanged("CardNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExpireDate {
            get {
                return this.expireDateField;
            }
            set {
                this.expireDateField = value;
                this.RaisePropertyChanged("ExpireDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CardName {
            get {
                return this.cardNameField;
            }
            set {
                this.cardNameField = value;
                this.RaisePropertyChanged("CardName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public AddressType BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
                this.RaisePropertyChanged("BillingAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime AuthorizationDate {
            get {
                return this.authorizationDateField;
            }
            set {
                this.authorizationDateField = value;
                this.RaisePropertyChanged("AuthorizationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AuthorizationDateSpecified {
            get {
                return this.authorizationDateFieldSpecified;
            }
            set {
                this.authorizationDateFieldSpecified = value;
                this.RaisePropertyChanged("AuthorizationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double AuthorizationAmount {
            get {
                return this.authorizationAmountField;
            }
            set {
                this.authorizationAmountField = value;
                this.RaisePropertyChanged("AuthorizationAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AuthorizationAmountSpecified {
            get {
                return this.authorizationAmountFieldSpecified;
            }
            set {
                this.authorizationAmountFieldSpecified = value;
                this.RaisePropertyChanged("AuthorizationAmountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oracle.com/soasample")]
    public partial class AddressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string[] addressLineField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipCodeField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressLine", Order=2)]
        public string[] AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
                this.RaisePropertyChanged("AddressLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oracle.com/soasample")]
    public partial class PaymentStatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.oracle.com/soasample", Order=0)]
        public SOA_FrontEnd.PaymentValidationReference.PaymentType PaymentInfo;
        
        public validateRequest() {
        }
        
        public validateRequest(SOA_FrontEnd.PaymentValidationReference.PaymentType PaymentInfo) {
            this.PaymentInfo = PaymentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.oracle.com/soasample", Order=0)]
        public SOA_FrontEnd.PaymentValidationReference.PaymentStatusType PaymentStatus;
        
        public validateResponse() {
        }
        
        public validateResponse(SOA_FrontEnd.PaymentValidationReference.PaymentStatusType PaymentStatus) {
            this.PaymentStatus = PaymentStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface validatePaymentPortTypeChannel : SOA_FrontEnd.PaymentValidationReference.validatePaymentPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class validatePaymentPortTypeClient : System.ServiceModel.ClientBase<SOA_FrontEnd.PaymentValidationReference.validatePaymentPortType>, SOA_FrontEnd.PaymentValidationReference.validatePaymentPortType {
        
        public validatePaymentPortTypeClient() {
        }
        
        public validatePaymentPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public validatePaymentPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public validatePaymentPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public validatePaymentPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA_FrontEnd.PaymentValidationReference.validateResponse SOA_FrontEnd.PaymentValidationReference.validatePaymentPortType.validate(SOA_FrontEnd.PaymentValidationReference.validateRequest request) {
            return base.Channel.validate(request);
        }
        
        public SOA_FrontEnd.PaymentValidationReference.PaymentStatusType validate(SOA_FrontEnd.PaymentValidationReference.PaymentType PaymentInfo) {
            SOA_FrontEnd.PaymentValidationReference.validateRequest inValue = new SOA_FrontEnd.PaymentValidationReference.validateRequest();
            inValue.PaymentInfo = PaymentInfo;
            SOA_FrontEnd.PaymentValidationReference.validateResponse retVal = ((SOA_FrontEnd.PaymentValidationReference.validatePaymentPortType)(this)).validate(inValue);
            return retVal.PaymentStatus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA_FrontEnd.PaymentValidationReference.validateResponse> SOA_FrontEnd.PaymentValidationReference.validatePaymentPortType.validateAsync(SOA_FrontEnd.PaymentValidationReference.validateRequest request) {
            return base.Channel.validateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA_FrontEnd.PaymentValidationReference.validateResponse> validateAsync(SOA_FrontEnd.PaymentValidationReference.PaymentType PaymentInfo) {
            SOA_FrontEnd.PaymentValidationReference.validateRequest inValue = new SOA_FrontEnd.PaymentValidationReference.validateRequest();
            inValue.PaymentInfo = PaymentInfo;
            return ((SOA_FrontEnd.PaymentValidationReference.validatePaymentPortType)(this)).validateAsync(inValue);
        }
    }
}
